### ISSUE TITLE
Project doesn't seem to be working for main OSs

### ISSUE THREAD

**Issue by luizperes** [luizperes/simdjson_nodejs#6]
It seems that `simd_nodejs` on the master branch is only currently working for Linux (the current tag version `0.0.2` on `npm` has only been tested with Mac and seems to be fine.

At the moment, we have two reported error in Windows and Mac:
- Windows: #1
- Mac: (see output below)

```
d142-058-221-020:simdjson_nodejs luizperes$ npm run build

> simdjson@0.0.2 build /Users/luizperes/Projects/simdjson_nodejs
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/simdjson/simdjson/main.o
In file included from ../simdjson/main.cpp:2:
In file included from ../simdjson/bindings.h:2:
../simdjson/src/simdjson.h:74:2: warning: "BMI is missing?" [-W#warnings]
#warning "BMI is missing?"
 ^
../simdjson/src/simdjson.h:35739:2: warning: "We require AVX2 support!" [-W#warnings]
#warning "We require AVX2 support!"
 ^
2 warnings generated.
  CXX(target) Release/obj.target/simdjson/simdjson/bindings.o
In file included from ../simdjson/bindings.cpp:1:
In file included from ../simdjson/bindings.h:2:
../simdjson/src/simdjson.h:74:2: warning: "BMI is missing?" [-W#warnings]
#warning "BMI is missing?"
 ^
../simdjson/src/simdjson.h:35739:2: warning: "We require AVX2 support!" [-W#warnings]
#warning "We require AVX2 support!"
 ^
2 warnings generated.
  CXX(target) Release/obj.target/simdjson/simdjson/src/simdjson.o
In file included from ../simdjson/src/simdjson.cpp:2:
../simdjson/src/simdjson.h:74:2: warning: "BMI is missing?" [-W#warnings]
#warning "BMI is missing?"
 ^
../simdjson/src/simdjson.h:35739:2: warning: "We require AVX2 support!" [-W#warnings]
#warning "We require AVX2 support!"
 ^
../simdjson/src/simdjson.cpp:408:34: error: variable has incomplete type 'struct avx_processed_utf_bytes'
  struct avx_processed_utf_bytes previous{};
                                 ^
../simdjson/src/simdjson.cpp:408:10: note: forward declaration of 'avx_processed_utf_bytes'
  struct avx_processed_utf_bytes previous{};
         ^
2 warnings and 1 error generated.
make: *** [Release/obj.target/simdjson/simdjson/src/simdjson.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/luizperes/Projects/simdjson_nodejs
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simdjson@0.0.2 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simdjson@0.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luizperes/.npm/_logs/2019-03-03T08_12_36_813Z-debug.log
```

It seems that the flags `__AVX2__` and `BMI` are not being recognized on Mac OS (it was tested outside `npm` and runs fine)

**Comment by luizperes** [comment]
Here goes a list of the tested OSs.:

- [ ] Linux
- [ ] Mac OS
- [ ] Windows

**Comment by luizperes** [comment]
Help needed for windows, removing that from `WIP` since I don't have a windows machine

**Comment by lemire** [comment]
This may get resolved with the next version of simdjson. Upstream, simdjson will provide runtime dispatch. 

cc @ioioioio

**Comment by luizperes** [comment]
Hi @lemire, I still need help for testing if it is working on Windows. For this reason I won't close it right now, cheers!

cc @ioioioio

**Comment by luizperes** [comment]
PR #27 fixes this issue
